/**
 * Port of src/util/dates.js — VERBATIM apart from the module syntax.
 *
 * Every function below is pure JavaScript over Intl and Date, both of which
 * workerd implements with the full ICU tz database, so nothing here needed to
 * change. In particular the DST behaviour of nextOccurrences is preserved
 * exactly: occurrences are generated by walking the LOCAL Baltimore calendar a
 * day at a time and converting each candidate through localInputToUtcIso, never
 * by adding 7 * 24h to a UTC instant (which would drift by an hour across the
 * November fall-back and turn a 5:30 PM Monday into 4:30 PM).
 *
 * If a line here ever diverges from src/util/dates.js, that is a bug in one of
 * the two files, not a port decision.
 */

import config from '../config.js';

const TZ = config.timezone; // America/New_York

/*
 * Storage rule for the whole app: every timestamp column holds an ISO-8601 UTC
 * string. These helpers are the only place that knows about Baltimore time.
 */

function fmt(opts) {
  return new Intl.DateTimeFormat('en-US', { timeZone: TZ, ...opts });
}

function toDate(value) {
  if (value instanceof Date) return value;
  if (typeof value === 'number') return new Date(value);
  if (typeof value === 'string' && value) {
    // Accept both "2026-08-10T22:30:00.000Z" and SQLite's "2026-08-10 22:30:00"
    const s = value.includes('T') || value.endsWith('Z') ? value : `${value.replace(' ', 'T')}Z`;
    const d = new Date(s);
    if (!Number.isNaN(d.getTime())) return d;
  }
  return null;
}

/** Milliseconds that must be subtracted from a wall-clock reading to get UTC. */
function tzOffsetMs(date) {
  const parts = fmt({
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
  }).formatToParts(date).reduce((acc, p) => ((acc[p.type] = p.value), acc), {});
  const asUtc = Date.UTC(
    Number(parts.year), Number(parts.month) - 1, Number(parts.day),
    Number(parts.hour) % 24, Number(parts.minute), Number(parts.second)
  );
  return asUtc - date.getTime();
}

/**
 * "2026-08-10T18:30" (what <input type="datetime-local"> submits, read as
 * Baltimore wall time) -> ISO UTC string. DST-correct via two-pass fixup.
 */
function localInputToUtcIso(input) {
  const m = /^(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2})/.exec(String(input || '').trim());
  if (!m) return null;
  const [, Y, M, D, h, mi] = m.map(Number);
  const naive = Date.UTC(Y, M - 1, D, h, mi);
  let ts = naive;
  for (let i = 0; i < 2; i += 1) ts = naive - tzOffsetMs(new Date(ts));
  const d = new Date(ts);
  return Number.isNaN(d.getTime()) ? null : d.toISOString();
}

/** ISO UTC -> "2026-08-10T18:30" for pre-filling a datetime-local input. */
function utcIsoToLocalInput(value) {
  const d = toDate(value);
  if (!d) return '';
  const p = fmt({
    year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', hour12: false,
  }).formatToParts(d).reduce((acc, x) => ((acc[x.type] = x.value), acc), {});
  return `${p.year}-${p.month}-${p.day}T${String(Number(p.hour) % 24).padStart(2, '0')}:${p.minute}`;
}

/** "Sunday, August 10, 2026" */
const formatDate = (v) => {
  const d = toDate(v);
  return d ? fmt({ weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(d) : '';
};

/** "Sun, Aug 10" */
const formatDateShort = (v) => {
  const d = toDate(v);
  return d ? fmt({ weekday: 'short', month: 'short', day: 'numeric' }).format(d) : '';
};

/** "Aug 10" — no weekday, for badges where every character costs width. */
const formatDateTiny = (v) => {
  const d = toDate(v);
  return d ? fmt({ month: 'short', day: 'numeric' }).format(d) : '';
};

/** "6:30 PM" */
const formatTime = (v) => {
  const d = toDate(v);
  return d ? fmt({ hour: 'numeric', minute: '2-digit', hour12: true }).format(d) : '';
};

/** "Sunday, August 10, 2026 · 6:30 PM" */
const formatDateTime = (v) => {
  const d = toDate(v);
  return d ? `${formatDate(d)} · ${formatTime(d)}` : '';
};

/** "SUNDAY" — for the mono eyebrow. */
const weekday = (v) => {
  const d = toDate(v);
  return d ? fmt({ weekday: 'long' }).format(d) : '';
};

/** Value for <time datetime="…">. */
const isoAttr = (v) => {
  const d = toDate(v);
  return d ? d.toISOString() : '';
};

/* ------------------------------------------------ weekly recurrence math ---
 * Recurring rules store a weekday (0 = Sunday) plus a local wall-clock "HH:MM".
 * Occurrences are generated by walking the LOCAL calendar a day at a time and
 * converting each candidate through localInputToUtcIso — never by adding
 * 7 * 24h to a UTC instant, which would drift by an hour across a DST boundary
 * (a 5:30 PM Monday would become 4:30 PM after the November fall-back).
 */

const WEEKDAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

/** "Saturday" from a stored weekday number, or '' if it is out of range. */
const weekdayName = (n) => WEEKDAY_NAMES[Number(n)] || '';

/** All seven names, for building a <select>. */
const weekdayNames = () => WEEKDAY_NAMES.slice();

/** Local Baltimore calendar date of an instant, as "YYYY-MM-DD". */
function localDateKey(v) {
  const d = toDate(v) || new Date();
  const p = fmt({ year: 'numeric', month: '2-digit', day: '2-digit' })
    .formatToParts(d)
    .reduce((acc, x) => ((acc[x.type] = x.value), acc), {});
  return `${p.year}-${p.month}-${p.day}`;
}

/** "13:00" -> "1:00 PM". Formats a stored wall-clock time with no date attached. */
function formatHhmm(hhmm) {
  const m = /^(\d{1,2}):(\d{2})$/.exec(String(hhmm || '').trim());
  if (!m) return '';
  const h = Number(m[1]) % 24;
  const suffix = h < 12 ? 'AM' : 'PM';
  return `${h % 12 === 0 ? 12 : h % 12}:${m[2]} ${suffix}`;
}

/** Normalise anything an <input type="time"> may submit to "HH:MM", or null. */
function normalizeHhmm(value) {
  const m = /^(\d{1,2}):(\d{2})/.exec(String(value || '').trim());
  if (!m) return null;
  const h = Number(m[1]);
  const mi = Number(m[2]);
  if (h > 23 || mi > 59) return null;
  return `${String(h).padStart(2, '0')}:${String(mi).padStart(2, '0')}`;
}

/** Add `days` to a "YYYY-MM-DD" local date key, purely as calendar arithmetic. */
function addLocalDays(key, days) {
  const [Y, M, D] = key.split('-').map(Number);
  const d = new Date(Date.UTC(Y, M - 1, D + days));
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
}

/** Day of week (0 = Sunday) for a "YYYY-MM-DD" local date key. */
function localDayOfWeek(key) {
  const [Y, M, D] = key.split('-').map(Number);
  return new Date(Date.UTC(Y, M - 1, D)).getUTCDay();
}

/**
 * The next `count` occurrences of "every <weekday> at <time_hhmm>", counted
 * from `from` (default: now) in Baltimore wall-clock terms.
 *
 * Returns [{ local_date: 'YYYY-MM-DD', starts_at: ISO UTC, date: Date }, …].
 * An occurrence happening later today counts; one that already started does not.
 */
function nextOccurrences(weekdayNum, time_hhmm, count = 1, from = new Date()) {
  const wd = Number(weekdayNum);
  const time = normalizeHhmm(time_hhmm);
  if (!Number.isInteger(wd) || wd < 0 || wd > 6 || !time) return [];
  const n = Math.max(0, Number(count) || 0);
  if (!n) return [];

  const fromDate = toDate(from) || new Date();
  const today = localDateKey(fromDate);
  let key = addLocalDays(today, (wd - localDayOfWeek(today) + 7) % 7);

  const out = [];
  // At most one extra hop: the only candidate that can be in the past is today's.
  for (let guard = 0; out.length < n && guard < n + 2; guard += 1) {
    const iso = localInputToUtcIso(`${key}T${time}`);
    const d = iso ? new Date(iso) : null;
    if (d && d.getTime() > fromDate.getTime()) {
      out.push({ local_date: key, starts_at: iso, date: d });
    }
    key = addLocalDays(key, 7);
  }
  return out;
}

/** "in 3 days" / "tomorrow" / "2 hours ago" — coarse and friendly. */
function relative(v) {
  const d = toDate(v);
  if (!d) return '';
  const diff = d.getTime() - Date.now();
  const abs = Math.abs(diff);
  const rtf = new Intl.RelativeTimeFormat('en-US', { numeric: 'auto' });
  const units = [
    ['year', 365 * 24 * 3600e3], ['month', 30 * 24 * 3600e3], ['week', 7 * 24 * 3600e3],
    ['day', 24 * 3600e3], ['hour', 3600e3], ['minute', 60e3],
  ];
  for (const [unit, ms] of units) {
    if (abs >= ms) return rtf.format(Math.round(diff / ms), unit);
  }
  return 'just now';
}

const nowIso = () => new Date().toISOString();

export {
  TZ,
  toDate,
  nowIso,
  localInputToUtcIso,
  utcIsoToLocalInput,
  formatDate,
  formatDateShort,
  formatDateTiny,
  formatTime,
  formatDateTime,
  weekday,
  weekdayName,
  weekdayNames,
  localDateKey,
  localDayOfWeek,
  addLocalDays,
  formatHhmm,
  normalizeHhmm,
  nextOccurrences,
  isoAttr,
  relative,
};
